import api from './axios';
export const getDashboard    = () => api.get('/teacher/dashboard');
export const getModules      = () => api.get('/teacher/modules');
export const getSchoolConfig = () => api.get('/profile/school-config');
export const getMySection   = () => api.get('/teacher/my-section');
export const createAnnouncement = (data) => api.post('/teacher/announcements', data);
export const deleteAnnouncement = (id) => api.delete(`/teacher/announcements/${id}`);
export const getAttendance  = (params) => api.get('/teacher/attendance', { params });
export const markAttendance = (data) => api.post('/teacher/attendance/mark', data);
export const getMyAttendance       = (params) => api.get('/teacher/my-attendance', { params });
export const markMyAttendance      = (data)   => api.post('/teacher/my-attendance/mark', data);
export const submitRegularization  = (data)   => api.post('/teacher/regularization', data);
export const getCorrectionRequests = ()       => api.get('/teacher/correction-requests');
export const reviewCorrection      = (data)   => api.post('/teacher/correction-requests/review', data);
export const getTimetable          = (params) => api.get('/teacher/timetable', { params });
export const downloadTimetable     = ()       => api.get('/teacher/timetable/download', { responseType: 'blob' });
export const getClassTimetable     = ()       => api.get('/teacher/timetable/my-class');
export const getExams       = () => api.get('/teacher/exams');
export const createExam     = (data) => api.post('/teacher/exams', data);
export const getExam        = (id) => api.get(`/teacher/exams/${id}`);
export const updateExam     = (id, data) => api.put(`/teacher/exams/${id}`, data);
export const deleteExam     = (id) => api.delete(`/teacher/exams/${id}`);
export const publishExam    = (id) => api.post(`/teacher/exams/${id}/publish`);
export const getQuestions   = (id) => api.get(`/teacher/exams/${id}/questions`);
export const addQuestion    = (id, data) => api.post(`/teacher/exams/${id}/questions`, data);
export const updateQuestion = (id, qid, data) => api.put(`/teacher/exams/${id}/questions/${qid}`, data);
export const deleteQuestion = (id, qid) => api.delete(`/teacher/exams/${id}/questions/${qid}`);
export const getSubmissions = (id) => api.get(`/teacher/exams/${id}/submissions`);
export const getAnalytics   = (id) => api.get(`/teacher/exams/${id}/analytics`);
export const getMyLeaves     = (params) => api.get('/teacher/leave', { params });
export const getLeaveBalance = ()       => api.get('/teacher/leave/balance');
export const applyLeave      = (data)   => api.post('/teacher/leave/apply', data);
export const cancelLeave     = (id)     => api.delete(`/teacher/leave/${id}`);
export const getDocuments   = () => api.get('/teacher/documents');
export const getHolidays         = () => api.get('/teacher/holidays');
export const getClassHolidays    = () => api.get('/teacher/class-holidays');
export const getMarksEntry  = () => api.get('/teacher/results/marks-entry');
export const getMarksForm   = (examId, subjectId) => api.get(`/teacher/results/marks-entry/${examId}/${subjectId}`);
export const saveMarks      = (examId, subjectId, data) => api.post(`/teacher/results/marks-entry/${examId}/${subjectId}/save`, data);
export const getClassTests  = () => api.get('/teacher/results/class-tests');
export const createClassTest = (data) => api.post('/teacher/results/class-tests', data);
