import api from './axios';
export const getDashboard    = () => api.get('/teacher/dashboard');
export const getModules      = () => api.get('/teacher/modules');
export const getSchoolConfig = () => api.get('/profile/school-config');
export const getMySection   = () => api.get('/teacher/my-section');
export const createAnnouncement = (data) => api.post('/teacher/announcements', data);
export const deleteAnnouncement = (id) => api.delete(`/teacher/announcements/${id}`);
export const getAttendance  = (params) => api.get('/teacher/attendance', { params });
export const markAttendance = (data) => api.post('/teacher/attendance/mark', data);
export const getMyAttendance       = (params) => api.get('/teacher/my-attendance', { params });
export const clockIn               = ()       => api.post('/teacher/my-attendance/clock-in');
export const clockOut              = ()       => api.post('/teacher/my-attendance/clock-out');
export const submitRegularization  = (data)   => api.post('/teacher/regularization', data);
export const getMyRegularizations  = ()       => api.get('/teacher/regularization');
export const getCorrectionRequests = ()       => api.get('/teacher/correction-requests');
export const getClassRanking       = ()       => api.get('/teacher/attendance-ranking');
export const reviewCorrection      = (data)   => api.post('/teacher/correction-requests/review', data);
export const getTimetable          = (params) => api.get('/teacher/timetable', { params });
export const downloadTimetable     = ()       => api.get('/teacher/timetable/download', { responseType: 'blob' });
export const getClassTimetable     = ()       => api.get('/teacher/timetable/my-class');
export const getExams       = () => api.get('/teacher/exams');
export const createExam     = (data) => api.post('/teacher/exams', data);
export const getExam        = (id) => api.get(`/teacher/exams/${id}`);
export const updateExam     = (id, data) => api.put(`/teacher/exams/${id}`, data);
export const deleteExam     = (id) => api.delete(`/teacher/exams/${id}`);
export const publishExam    = (id) => api.post(`/teacher/exams/${id}/publish`);
export const getQuestions   = (id) => api.get(`/teacher/exams/${id}/questions`);
export const addQuestion    = (id, data) => api.post(`/teacher/exams/${id}/questions`, data);
export const updateQuestion = (id, qid, data) => api.put(`/teacher/exams/${id}/questions/${qid}`, data);
export const deleteQuestion = (id, qid) => api.delete(`/teacher/exams/${id}/questions/${qid}`);
export const getSubmissions = (id) => api.get(`/teacher/exams/${id}/submissions`);
export const getAnalytics   = (id) => api.get(`/teacher/exams/${id}/analytics`);
export const getExamMeta          = ()   => api.get('/teacher/exams/meta');
export const getStudentResponse   = (id, studentId) => api.get(`/teacher/exams/${id}/submissions/${studentId}`);
export const getResultApproval    = (id) => api.get(`/teacher/exams/${id}/result-approval`);
export const subjectApproveResults= (id) => api.post(`/teacher/exams/${id}/subject-approve`);
export const approveResults       = (id, data) => api.post(`/teacher/exams/${id}/result-approval`, data);
export const getMyLeaves     = (params) => api.get('/teacher/leave', { params });
export const getLeaveBalance = ()       => api.get('/teacher/leave/balance');
export const applyLeave      = (data)   => api.post('/teacher/leave/apply', data);
export const cancelLeave     = (id)     => api.delete(`/teacher/leave/${id}`);
export const getDocumentCategories = () => api.get('/teacher/document-categories');
export const getDocuments          = (params) => api.get('/teacher/documents', { params });
export const uploadDocument      = (data)   => api.post('/teacher/documents', data);
export const getDocument         = (id)     => api.get(`/teacher/documents/${id}`);
export const updateDocument      = (id, data) => api.put(`/teacher/documents/${id}`, data);
export const deleteDocument      = (id)     => api.delete(`/teacher/documents/${id}`);
export const getDocumentSubs     = (id)     => api.get(`/teacher/documents/${id}/submissions`);
export const reviewSubmission    = (subId, data) => api.post(`/teacher/documents/submissions/${subId}/review`, data);
export const getHolidays         = () => api.get('/teacher/holidays');
export const getClassHolidays    = () => api.get('/teacher/class-holidays');
export const getMarksEntry  = () => api.get('/teacher/results/marks-entry');
export const getMarksForm   = (examId, subjectId) => api.get(`/teacher/results/marks-entry/${examId}/${subjectId}`);
export const saveMarks      = (examId, subjectId, data) => api.post(`/teacher/results/marks-entry/${examId}/${subjectId}/save`, data);
export const getValidation        = () => api.get('/teacher/results/validation');
export const getValidationDetail  = (examId) => api.get(`/teacher/results/validation/${examId}`);
export const approveValidation    = (examId, data) => api.post(`/teacher/results/validation/${examId}/approve`, data);
export const rejectValidation     = (examId, data) => api.post(`/teacher/results/validation/${examId}/reject`, data);
export const getClassTests  = () => api.get('/teacher/results/class-tests');
export const createClassTest = (data) => api.post('/teacher/results/class-tests', data);
export const getTestMarks    = (id) => api.get(`/teacher/results/class-tests/${id}/marks`);
export const saveTestMarks   = (id, data) => api.post(`/teacher/results/class-tests/${id}/marks/save`, data);
